### ISSUE TITLE
"Peter" DJ (Crew Leader) disapeared from Employee list and can not be added back in.

### ISSUE THREAD

**Issue by peter8rossi** [mdjm/mobile-dj-manager#228]
I have access to the website as the site administrator but I no longer show as an employee and I can not add myself back. The two other DJ (or Crew Leaders in our case - including Mike Howard) are still showing and can be selected for an event. In my user profile there is no MDJM role selection, but the heading for MDJM management is there and additional capabilities box is full (see attached screen capture).

![capture - capabilities](https://user-images.githubusercontent.com/19335843/46825296-4e101a00-cd61-11e8-822c-680f96d29c61.JPG)

I updated Java this morning but everything worked fine afterwards. I also updated by password. The only plug in update was done after I saw this problem.

**Comment by mikeyhoward1977** [comment]
I have fixed this for you. If you see this in future, have another admin login and edit your user account. Go to the option *TagParty Employee Role* and ensure that the correct role is selected. Then save,

If you have any further issues, please open a support ticket via mdjm.co.uk
